const express = require('express');
const cors = require('cors');
const applicationRoutes = require('./routes/applications.routes');
const app = express();
app.use(cors());
app.use(express.json());
app.use('/api/applications', applicationRoutes);
app.get('/health', (req, res) => res.status(200).json({ status: 'ok' }));
app.use((err, req, res, next) => { console.error(err.stack); res.status(err.status || 500).json({ error: err.message || 'Internal Server Error' }); });
module.exports = app;
